name: FigAdmin
main: com.btbb.figadmin.FigAdmin
version: 5.0.2
website: http://www.bobtheblueberry.com
author: Serge Humphrey
description: >
             Admin plugin for Bukkit, adds important functions like kicking and banning.
commands:
  kick:
    description: Kick a player
    usage: /<command> player [reason] - Kick a player
  tempban:
    description: Temporarily ban a player
    usage: /<command> player time timeform [reason] - Temporarily ban a player
  ban:
    description: Ban a player
    usage: /<command> player [reason] - Ban a player
  unban:
    description: Unban a player
    usage: /<command> player - Unban a player
  unbanip:
    description: Unbans players with IP
    usage: /<command> IP - Unbans players with given IP
  checkban:
    description: Check if a player is banned
    usage: /<command> [player]
  reloadfig:
    description: Reload the entire plugin.
    usage: /<command>
  figadmin:
    description: Displays version.
    usage: /<command> 
  ipban:
    description: Turns IP banning on|off
    usage: /<command> on|off
  exportbans:
    description: Export bans to banned-players.json and ip-bans.json
    usage: /<command>
  warn:
    description: Warn a player
    usage: /<command> player reason - Warn a player
  clearwarnings:
    description: Clears all warnings for given player 
    usage: /<command> player 
    aliases: clearplayer
  editban:
    description: Edit a ban
    usage: /<command> <list/search/select/load/save/show/reason/time/ip/delete/cancel>
    aliases: [eb,eban]
